name: IntegrationTest

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch for integration tests'     
        required: true
        default: 'develop'

jobs:
  integration-test:
    runs-on: ubuntu-latest
    container: openroberta/base:25
    steps:
      - name: Select the branch
        id: branchSelection
        run: |
          if ${{ github.event_name == 'workflow_dispatch' }}
          then
            echo "::set-output name=ref::refs/heads/${{ github.event.inputs.branch }}"
          elif ${{ github.event_name == 'schedule' }}
          then
            echo "::set-output name=ref::refs/heads/develop"
          else
            echo "::set-output name=ref::${{ github.ref }}"
          fi
      - name: Run integration tests for branch ${{steps.branchSelection.outputs.ref}} of repo ${{ github.repository }}
        run: echo "Run integration tests for branch ${{steps.branchSelection.outputs.ref}} of repo ${{ github.repository }}"
      - name: Checkout the selected branch
        uses: actions/checkout@v2
        with:
          ref: ${{steps.branchSelection.outputs.ref}}
      - name: Setup Java JDK
        uses: actions/setup-java@v2.1.0
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache local maven repository
        uses: actions/cache@v2
        with:
          path: /root/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with maven and run integration tests
        run: mvn --batch-mode clean install -PrunIT
